# Generated by Django 4.2.5 on 2024-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_perfilempleado_remove_servicio_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempleado',
            name='referencia1_nombre',
            field=models.CharField(default='Sin referencia', max_length=45),
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='referencia1_telefono',
            field=models.CharField(default='Sin teléfono', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='referencia2_nombre',
            field=models.CharField(default='Sin referencia', max_length=45),
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='referencia2_telefono',
            field=models.CharField(default='Sin teléfono', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='referencia3_nombre',
            field=models.CharField(default='Sin referencia', max_length=45),
        ),
        migrations.AddField(
            model_name='perfilempleado',
            name='referencia3_telefono',
            field=models.CharField(default='Sin teléfono', max_length=15),
        ),
    ]
