# Generated by Django 4.2.5 on 2024-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_perfilempleado_referencia1_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempleado',
            name='servicios_calificados',
            field=models.ManyToManyField(blank=True, related_name='empleados_calificados', to='users.servicio'),
        ),
    ]
